export const quotesGerman = [
  "Ein Bodybuilder ist ein Bildhauer, der sein eigenes Material bei sich trägt. - Serge Nubret",
  "Wenn deine Bodybuilding-Ziele höher werden, musst du offensichtlich härter arbeiten. - Reg Park",
  "Am Ende des Tages ist es kein Gewichtswettbewerb, es ist ein visueller Wettbewerb. - Dorian Yates",
  "Negativ und faul zu sein ist eine Krankheit, die zu Schmerzen, Schwierigkeiten, Depressionen, schlechter Gesundheit und Misserfolg führt. Sei proaktiv und gib einen Damm, um Erfolg zu erzielen! - Phil Heath",
  "Bodybuilding ist eine Kunst, dein Körper ist die Leinwand, Gewichte sind dein Pinsel und Ernährung ist deine Farbe. - Kai Greene",
  "Bodybuilding ist nicht nur ein Sport, sondern zuerst eine KUNST. - Serge Nubret",
  "Bodybuilding ist das Nächste, was wir am Jungbrunnen haben. - Lee Labrada",
  "Bodybuilding ist kein 90-minütiges Training im Fitnessstudio. Es ist ein Lebensstil. - Lee Priest",
  "Du kannst Ergebnisse oder Ausreden haben. Nicht beides. - Arnold Schwarzenegger",
  "Der Schmerz, den du heute fühlst, wird die Stärke sein, die du morgen fühlst. - Arnold Schwarzenegger",
  "Erfolg ist normalerweise die Krönung der Kontrolle des Scheiterns. - Sylvester Stallone",
  "Der einzige Weg zu wachsen ist, sich selbst herauszufordern. - Lou Ferrigno",
  "Schwitzen, opfern und Selbstdisziplin. - Arnold Schwarzenegger",
  "Jeder Champion war einmal ein Anwärter, der sich weigerte aufzugeben. - Rocky Balboa",
  "Wir können uns weiter pushen. Wir haben immer mehr zu geben. - Simone Biles",
  "Übung sollte als Tribut an das Herz angesehen werden. - Gene Tunney",
  "Ich weiß, dass ich etwas erreichen werde, wenn ich mir etwas in den Kopf setze, auch wenn die Leute sagen, dass ich es nicht schaffen kann. - David Beckham",
  "Ich glaube, dass das Training, wie es von anderen gesehen wird, nicht der Schlüssel zum Erfolg ist. Wir trainieren nicht um uns fit zu fühlen. Wir trainieren um besser zu werden. - David Goggins",
  "Erfolg ist die Summe kleiner Anstrengungen, die du Tag für Tag unternimmst. - Robert Collier",
  "Die Herausforderung besteht darin, die Grenzen deines Körpers zu überwinden und die Grenzen deines Geistes zu erweitern. - Arnold Schwarzenegger",
  "Du kannst nichts erreichen, wenn du keine Ziele setzt. - Arnold Schwarzenegger",
  "Die Härte der Straße wird dich stärker machen. - Dwayne 'The Rock' Johnson",
  "Der wahre Wert eines Menschen ist, wie er sich verhält, wenn niemand hinschaut. - John Wooden",
  "Dein Körper kann alles tun, solange dein Verstand mitspielt. - Arnold Schwarzenegger",
  "Der Schmerz, den du heute fühlst, wird die Stärke sein, die du morgen fühlst. - Jay Cutler",
  "Erfolg ist nicht der Schlüssel zum Glück. Glück ist der Schlüssel zum Erfolg. Wenn du liebst, was du tust, wirst du erfolgreich sein. - Albert Schweitzer",
  "Deine Einstellung entscheidet, ob du den Berg siehst oder die Steine. - Dwayne 'The Rock' Johnson",
  "Die einzige Grenze für das Erreichen deiner Ziele ist die, die du dir selbst setzt. - Roy T. Bennett",
  "Es ist nicht, wie hart du zuschlägst. Es geht darum, wie viele Schläge du einstecken kannst und trotzdem weitermachst. - Rocky Balboa",
  "Der einzige Wettbewerb sollte der sein, den du gegen dich selbst führst. - Mike Tyson",
  "Du musst die Dunkelheit überwinden, um das Licht zu sehen. - David Goggins",
  "Das Training ist wie das Atmen. Ich kann es nicht nicht tun. - Joe Weider",
  "Wenn du nicht an dich selbst glaubst, wird niemand sonst an dich glauben. - Kobe Bryant",
  "Die größte Leistung im Leben ist, dich selbst zu besiegen. - Arnold Schwarzenegger",
  "Erfolg ist eine Reise, nicht ein Ziel. Der doing ist oft wichtiger als das Ergebnis. - Arthur Ashe",
  "Die wahre Stärke liegt nicht darin, niemals zu fallen, sondern jedes Mal wieder aufzustehen, wenn du fällst. - Vince Lombardi",
  "Der Geist ist stärker als der Körper. Wenn du denkst, dass du es schaffst, wirst du es schaffen. - Muhammad Ali",
  "Schwierigkeiten stärken den Geist, wie Arbeit den Körper stärkt. - Arnold Schwarzenegger",
  "Glaube an dich selbst und alles ist möglich. Wisse, dass es im Inneren deiner Seele die Kraft gibt, die die Welt bewegt. - John Cena",
  "Erfolg kommt nicht zu dir, du gehst zu ihm. - Marv Levy",
  "Die größte Freude im Leben ist, Dinge zu tun, von denen die Leute sagen, dass du sie nicht tun kannst. - Walter Bagehot",
  "Warte nicht auf die Gelegenheit. Erschaffe sie. - George Bernard Shaw",
  "Deine Träume sind möglich. Wenn du es fühlst, kannst du es erreichen. - Tom Platz",
  "Die größten Erfolge beginnen mit dem Glauben an dich selbst. - Muhammad Ali",
  "Denke an Trainieren und Essen wie an Zahneputzen - etwas, das du einfach tust. - John Barardi",
  "Nimm dir Zeit, um zu träumen, es ist der Weg zu den Sternen. - Oscar Wilde",
  "Die einzige Wahl, die du nicht hast, ist die Wahl, dich selbst herauszufordern. - Tom Platz",
  "Der Körper erreicht, was der Geist glaubt. - Arnold Schwarzenegger",
  "Um erfolgreich zu sein, musst du die Dinge anders machen als die anderen. - Arnold Schwarzenegger",
  "Erfolg ist das Ergebnis von Perfektion, harter Arbeit, Lernen aus Niederlagen, Loyalität und Beharrlichkeit. - Colin Powell",
  "Wenn du nicht bereit bist, für deine Träume zu arbeiten, wirst du für jemand anderen arbeiten, um seine Träume zu verwirklichen. - Steve Jobs",
  "Ein starker Wille und Entschlossenheit können Berge versetzen. - John Newton",
  "Dein Körper kann alles tun, solange dein Geist mitspielt. - Arnold Schwarzenegger",
  "Nimm deine Träume ernst, aber nicht dich selbst. - Donny Osmond",
  "Das Schwierigste am Leben ist, Herz und Geist zu überzeugen, dass es wert ist, alles zu geben. - Arnold Schwarzenegger",
  "Die einzige Person, die dich aufhalten kann, bist du selbst. - Arnold Schwarzenegger",
  "Wenn du nicht bereit bist, für deine Träume zu arbeiten, wirst du für jemand anderen arbeiten, um seine Träume zu verwirklichen. - Steve Jobs",
  "Wenn du nicht an dich selbst glaubst, wird niemand sonst an dich glauben. - Kobe Bryant",
  "Der einzige Wettbewerb sollte der sein, den du gegen dich selbst führst. - Mike Tyson",
  "Die größte Leistung im Leben ist, dich selbst zu besiegen. - Arnold Schwarzenegger",
  "Erfolg ist eine Reise, nicht ein Ziel. Der doing ist oft wichtiger als das Ergebnis. - Arthur Ashe",
  "Der Geist ist stärker als der Körper. Wenn du denkst, dass du es schaffst, wirst du es schaffen. - Muhammad Ali",
  "Schwierigkeiten stärken den Geist, wie Arbeit den Körper stärkt. - Arnold Schwarzenegger",
  "Glaube an dich selbst und alles ist möglich. Wisse, dass es im Inneren deiner Seele die Kraft gibt, die die Welt bewegt. - John Cena",
  "Erfolg kommt nicht zu dir, du gehst zu ihm. - Marv Levy",
  "Die größte Freude im Leben ist, Dinge zu tun, von denen die Leute sagen, dass du sie nicht tun kannst. - Walter Bagehot",
  "Warte nicht auf die Gelegenheit. Erschaffe sie. - George Bernard Shaw",
  "Deine Träume sind möglich. Wenn du es fühlst, kannst du es erreichen. - Tom Platz",
  "Die größten Erfolge beginnen mit dem Glauben an dich selbst. - Muhammad Ali",
];

export const quotesEnglish = [
  "A bodybuilder is a sculptor who carries his own material with him. - Serge Nubret",
  "As your bodybuilding goals get higher, you obviously have to work harder. - Reg Park",
  "At the end of the day, it's not a weight competition, it's a visual competition. - Dorian Yates",
  "Being negative and lazy is a disease that leads to pain, difficulty, depression, poor health and failure. Be proactive and create a dam to achieve success! - Phil Heath",
  "Bodybuilding is an art, your body is the canvas, weights are your brush and nutrition is your paint. - Kai Greene",
  "Bodybuilding is not just a sport, but first of all an ART. - Serge Nubret",
  "Bodybuilding is the closest thing we have to the fountain of youth. - Lee Labrada",
  "Bodybuilding is not a 90-minute workout in the gym. It's a lifestyle. - Lee Priest",
  "You can have results or excuses. Not both. - Arnold Schwarzenegger",
  "The pain you feel today will be the strength you feel tomorrow. - Arnold Schwarzenegger",
  "Success is usually the pinnacle of controlling failure. - Sylvester Stallone",
  "The only way to grow is to challenge yourself. - Lou Ferrigno",
  "Sweat, sacrifice and self-discipline. - Arnold Schwarzenegger",
  "Every champion was once a contender who refused to give up. - Rocky Balboa",
  "We can keep pushing ourselves. We always have more to give. - Simone Biles",
  "Exercise should be viewed as a tribute to the heart. - Gene Tunney",
  "I know that when I put my mind to something, I will achieve it, even if people say I can't do it. - David Beckham",
  "I believe that training, as seen by others, is not the key to success. We don't train to feel fit. We train to get better. - David Goggins",
  "Success is the sum of small efforts you make day after day. - Robert Collier",
  "The challenge is to overcome the limits of your body and expand the limits of your mind. - Arnold Schwarzenegger",
  "You can't achieve anything if you don't set goals. - Arnold Schwarzenegger",
  "The harshness of the road will make you stronger. - Dwayne 'The Rock' Johnson",
  "The true value of a person is how they behave when no one is looking. - John Wooden",
  "Your body can do anything as long as your mind cooperates. - Arnold Schwarzenegger",
  "The pain you feel today will be the strength you feel tomorrow. - Jay Cutler",
  "Success is not the key to happiness. Happiness is the key to success. If you love what you do, you will be successful. - Albert Schweitzer",
  "Your attitude decides whether you see the mountain or the rocks. - Dwayne 'The Rock' Johnson",
  "The only limit to achieving your goals is the one you set for yourself. - Roy T. Bennett",
  "It's not how hard you hit. It's how many hits you can take and still keep going. - Rocky Balboa",
  "The only competition should be against yourself. - Mike Tyson",
  "You must overcome the darkness to see the light. - David Goggins",
  "Working out is like breathing. I can't not do it. - Joe Weider",
  "If you don't believe in yourself, no one else will believe in you. - Kobe Bryant",
  "The greatest achievement in life is defeating yourself. - Arnold Schwarzenegger",
  "Success is a journey, not a destination. The doing is often more important than the result. - Arthur Ashe",
  "True strength lies not in never falling, but in getting up every time you fall. - Vince Lombardi",
  "The mind is stronger than the body. If you think you can do it, you will do it. - Muhammad Ali",
  "Difficulties strengthen the mind as work strengthens the body. - Arnold Schwarzenegger",
  "Believe in yourself and anything is possible. Know that within your soul there is the power that moves the world. - John Cena",
  "Success doesn't come to you, you go to it. - Marv Levy",
  "The greatest joy in life is doing things that people say you can't do. - Walter Bagehot",
  "Don't wait for the opportunity. Create it. - George Bernard Shaw",
  "Your dreams are possible. If you feel it, you can achieve it. - Tom Platz",
  "The greatest successes begin with believing in yourself. - Muhammad Ali",
  "Think of exercising and eating like brushing your teeth - something you just do. - John Barardi",
  "Take time to dream, it's the way to the stars. - Oscar Wilde",
  "The only choice you don't have is the choice to challenge yourself. - Tom Platz",
  "The body achieves what the mind believes. - Arnold Schwarzenegger",
  "To be successful, you have to do things differently than others. - Arnold Schwarzenegger",
  "Success is the result of perfection, hard work, learning from failure, loyalty and persistence. - Colin Powell",
  "If you're not willing to work for your dreams, you'll work for someone else to make their dreams come true. - Steve Jobs",
  "A strong will and determination can move mountains. - John Newton",
  "Your body can do anything as long as your mind cooperates. - Arnold Schwarzenegger",
  "Take your dreams seriously, but not yourself. - Donny Osmond",
  "The most difficult thing in life is to convince your heart and mind that it is worth giving everything. - Arnold Schwarzenegger",
  "The only person who can stop you is yourself. - Arnold Schwarzenegger",
  "If you're not willing to work for your dreams, you'll work for someone else to make their dreams come true. - Steve Jobs",
  "If you don't believe in yourself, no one else will believe in you. - Kobe Bryant",
  "The only competition should be against yourself. - Mike Tyson",
  "The greatest achievement in life is defeating yourself. - Arnold Schwarzenegger",
  "Success is a journey, not a destination. The doing is often more important than the result. - Arthur Ashe",
  "The mind is stronger than the body. If you think you can do it, you will do it. - Muhammad Ali",
  "Difficulties strengthen the mind as work strengthens the body. - Arnold Schwarzenegger",
  "Believe in yourself and anything is possible. Know that within your soul there is the power that moves the world. - John Cena",
  "Success doesn't come to you, you go to it. - Marv Levy",
  "The greatest joy in life is doing things that people say you can't do. - Walter Bagehot",
  "Don't wait for the opportunity. Create it. - George Bernard Shaw",
  "Your dreams are possible. If you feel it, you can achieve it. - Tom Platz",
  "The greatest successes begin with believing in yourself. - Muhammad Ali",
];
